### ISSUE TITLE
Decoding fail

### ISSUE THREAD

**Issue by lgdu** [pigpeppa/xin26x#1]
command: 

`xin26x_test.exe -i BasketballDrive_1920x1080_50.yuv -w 1920 -h 1080 -f 50 -a 2 -p 1 -b 2000000 -o test.bin`

xinConfig:
InputFileName = BasketballDrive_1920x1080_50.yuv
OutputFileName = test.bin
ReconFileName =
inputWidth = 1920
inputHeight = 1080
STATUS: Xin26x lib build date: Aug 18 2020 21:17:24.

Start coding...
Complete coding.
501 frames encoded, coding speed fps:53.9057 bitrate: 2029.17 kbps.

`
./DecoderApp -b test.bin -o test.yuv
`

VVCSoftware: VTM Decoder Version 10.0 [Linux][GCC 7.5.0][64 bit] [SIMD=AVX2]

ERROR: In function "decompressSlice" in /home/ldu/VVCSoftware_VTM-VTM-10.0/source/Lib/DecoderLib/DecSlice.cpp:266: Expecting a terminating bit

 Total Time:        0.011 sec.

**Comment by pigpeppa** [comment]
i will look into it.

**Comment by pigpeppa** [comment]
Thanks for reporting. it is fixed now.  please try following command line:
xin26x_test.exe -i BasketballDrive_1920x1080_50.yuv -w 1920 -h 1080 -f 50 -a 2 -p 1 -r 1 -b 2000000 -o test.bin
