### ISSUE TITLE
How to run in linux?

### ISSUE THREAD

**Issue by 3togo** [pigpeppa/xin26x#10]
Where is the libxin26x.so? If not, can you provide one for testing?

/usr/bin/ld: CMakeFiles/xin26x_test.dir/__/common/source/xin_config_file.c.o:(.bss+0x0): multiple definition of `pfXin26xLogEntry'; CMakeFiles/xin26x_test.dir/source/xin_app_enc.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/xin26x_test.dir/__/common/source/xin_encoder_option.c.o:(.bss+0x0): multiple definition of `pfXin26xLogEntry'; CMakeFiles/xin26x_test.dir/source/xin_app_enc.c.o:(.bss+0x0): first defined here
/usr/bin/ld: cannot find -lxin26x
collect2: error: ld returned 1 exit status
make[2]: *** [app/encoder/CMakeFiles/xin26x_test.dir/build.make:133: app/encoder/xin26x_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: app/encoder/CMakeFiles/xin26x_test.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by georgepig** [comment]
we will release linux version soon.

**Comment by georgepig** [comment]
Now Linux 64bit dll is released.

**Comment by mj1028** [comment]
linux lib type should be .a or .so! would u mind to provide one for testing in linux environment?
using the latest code the error log as following

[ 25%] Building C object app/encoder/CMakeFiles/xin26x_test.dir/source/xin_app_enc.c.o
[ 50%] Building C object app/encoder/CMakeFiles/xin26x_test.dir/__/common/source/xin_config_file.c.o
[ 75%] Building C object app/encoder/CMakeFiles/xin26x_test.dir/__/common/source/xin_encoder_option.c.o
[100%] Linking C executable xin26x_test
/usr/bin/ld: cannot find -lxin26x
collect2: error: ld returned 1 exit status
make[2]: *** [app/encoder/CMakeFiles/xin26x_test.dir/build.make:114: app/encoder/xin26x_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: app/encoder/CMakeFiles/xin26x_test.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
