### ISSUE TITLE
Segfault on HEAD when encoding H266 with fixed QP

### ISSUE THREAD

**Issue by Akatmks** [pigpeppa/xin26x#14]
*Steps to reproduce:*  

1. Encode a video using `./xin26x_test.exe" -i "video.yuv" -a 2 -o "video.266" -w 1920 -h 1080 -f 24000/1001 -p 2`:  
    The encoding starts normally.  
2. Encode a video using `./xin26x_test.exe" -i "video.yuv" -a 2 -o "video.266" -w 1920 -h 1080 -f 24000/1001 -r 0 -q 20 -p 2`:  
    Segmentation fault.  

Last usable commit is around 497e50954e .  
Thanks.

**Comment by pigpeppa** [comment]
currently, xin26x under fixed qp is not available.
